export const INCREMENT_QTY = "INCREMENT_QTY";
export const DECREMENT_QTY = "DECREMENT_QTY";
export const SET_AUTH_STATUS = "SET_AUTH_STATUS";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const RELOAD_CART = "RELOAD_CART";
export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED"